### ISSUE TITLE
Error in py_call_impl

### ISSUE THREAD

**Issue by jesuiskelly** [EagerAI/fastai#119]
Hello, I followed this tutorial: https://henry090.github.io/fastai/articles/multilabel.html

And hit an error when I ran this line: learn %>% summary()

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: not enough values to unpack (expected 5, got 4)

Detailed traceback: 
  File "/mnt/hdd/Z_NLP_Classifier/07_Test_03/02_Code/renv/python/r-reticulate/lib/python3.6/site-packages/blurr/modeling/core.py", line 120, in blurr_summary
    res = blurr_module_summary(self, *xb)
  File "/mnt/hdd/Z_NLP_Classifier/07_Test_03/02_Code/renv/python/r-reticulate/lib/python3.6/site-packages/blurr/modeling/core.py", line 98, in blurr_module_summary
    for typ,np,trn,sz,chnged in infos:

Lastly, not sure if this is relevant, I modified the creation of blocks to be the following (whilst tutorial only include hf_arch and hf_tokenizer): 
blocks = list(
  HF_TextBlock(hf_arch, hf_config, hf_tokenizer, hf_model),
  MultiCategoryBlock(encoded=TRUE, vocab=lbl_cols))

Thank you very much in advance!

**Comment by henry090** [comment]
Please, try this ```reticulate::py_install('fastai==2.2.7 ohmeow-blurr',pip = T)```
Restart and rerun again. It worked for me.
Predictions can be obtained: ```learn %>% predict("Those damned affluent white people should only eat their own food, like cod cakes and boiled potatoes.
No enchiladas for them!") %>% .[[1]] %>% as_array()
```
Regarding the modified blocks, you are right. It would be great if you opened a PR for that. So, we can fix it.

**Comment by jesuiskelly** [comment]
Thanks for getting back to me. Happy to raise a PR afterwards.

I tried the line of command and it worked, but somehow Rstudio froze when I
ran the predict command. I'm trying to uninstall and reinstall and see if
this would help. Will report back later.

Thank you!
Kelly

**Comment by henry090** [comment]
Do you use CPU/GPU for prediction? CPU can cause issues

**Comment by jesuiskelly** [comment]
Hi oh that’s a good point! We have CPU :(

Is there a way we can make it work?

And sorry not got round to try after re-installation as it’s full on at work at the moment.

Kelly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by henry090** [comment]
I think you could run your case on Colab. Here is an example how to set up fast.ai there https://colab.research.google.com/drive/1PiBECDM552No-5apVIB8LqUSdSqqJSi-?usp=sharing

**Comment by jesuiskelly** [comment]
Great thank will have a look soon! And sorry for the delay in getting back
to you --in the middle of a project, so hopefully come back to this in the
next two weeks.
Thanks!
Kelly

**Comment by henry090** [comment]
Please, reopen if you still face issues.

**Comment by jesuiskelly** [comment]
Thanks. Yes agreed. Sorry, been snowed under lately. Hope to come back to
this soon.
K
