### ISSUE TITLE
Potential error in TextBlock_from_df ?

### ISSUE THREAD

**Issue by Cdk29** [EagerAI/fastai#135]
Hi. I am not sure why but I got trouble running TextBlock_from_df().
I have a data.table looking like the following : 

> Id | text_article | label
> 
> d0fa7568-7d8e-4db9-870f-f9c6f668c17b | What is this study about? This study used data from the National Education Longitudinal Study (NELS:88) to examine the effects of dual enrollment programs for high school students on college degree attainment | national education longitudinal study
> 

I am trying to run : 

```
data_block = DataBlock(
             blocks = list(TextBlock_from_df(text_cols="text_article")),  #List() is required on the R side.
             get_x=ColReader("text_article"), 
             get_y=ColReader('label'))

```
According to the example here https://docs.fast.ai/text.data.html#TextBlock.from_df and here : https://github.com/EagerAI/fastai#text-data and the fastai books.

But I also tried directly : 

`data_block = DataBlock(blocks = list(TextBlock_from_df(text_cols="text_article"))) #from fastai doc`

Both gave me the following error : 

> **Error: $ operator is invalid for atomic vectors**
> Traceback:
> 
> 1. DataBlock(blocks = list(TextBlock_from_df(text_cols = "text_article")))
> 2. TextBlock_from_df(text_cols = "text_article")
> 3. **do.call(text()$TextBlock$from_df, args)**

I put in bold what attract my suspicion. I am not really at home here, I am doing NLP with fastai for the first time, both in R and fastai as well.
I am putting the name of the column directly as a string, "text_article"  as I am supposed to do. Based on the examples the dataframe with the text is supposed to be provided after. For what I understand the fastai wrapper is not happy about the text()$TextBlock$from_df).

**Comment by Cdk29** [comment]
Just realized that I am installing fastai with the install.package. I am retrying with devtools and install from github.

**Comment by henry090** [comment]
Hi, could you remove fastai and reinstall, please? I would remove the existing py env or install to the new one.

**Comment by Cdk29** [comment]
I am running the following and got the same error : 

```
blocks = list(TextBlock_from_df(text_cols="text_article"), CategoryBlock())

#creation of the TextBlock object
#cf page 342 from the fastai book.
#name of the column, not directly the dataframe with the $ operator

data_block = DataBlock(
             blocks = blocks,  #List() is required on the R side.
             get_x=ColReader("text_article"), 
             get_y=ColReader('label')) #from fastai doc
             #splitter=RandomSplitter(0.1)) #page 342
```

*Error: $ operator is invalid for atomic vectors
Traceback:

1. TextBlock_from_df(text_cols = "text_article")
2. do.call(text()$TextBlock$from_df, args)

@henry090 I am try to do this on kaggle ^^ do you want to access the notebook?

**Comment by henry090** [comment]
Yes, please. But I can take a look in a couple of hours.

**Comment by Cdk29** [comment]
No problem I am not in a hurry with this.
Done !

**Comment by Cdk29** [comment]
Looking the tutorial here : https://docs.fast.ai/tutorial.text.html 

I tried to run : 

`text<-reticulate::import("fastai.text.all")`

Which gave : 

> Error in py_module_import(module, convert = convert): AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'

I have put it in the notebook where I have added you as a collaborator if you want to take a look.

**Comment by Cdk29** [comment]
Running :  

`reticulate::virtualenv_install(packages="fastai")`

Solved the issue of : 

`text<-reticulate::import("fastai.text.all")
`
Trying to create a datablock like this : 

```
data_block = DataBlock(
             blocks = blocks,  #List() is required on the R side.
             get_x=ColReader("text_article"), 
             get_y=ColReader('label')) #from fastai doc
             #splitter=RandomSplitter(0.1)) #page 342
```

Does not raise any errors any more after installing fastai with recitulate. **Disclaimer : I do not know yet if it is working properly.**

So maybe something is actually missing in` fastai::install_fastai(gpu = TRUE) `?

**Comment by henry090** [comment]
Hi. Sorry for the late reply. I reinstalled on my local and it works with Cuda 11 and gpu=T. Could you add a test to fast.ai repo so will see whether the data block works for text or not? Just data loading (not training)

**Comment by Cdk29** [comment]
Sure. You can assign me to this.

For the reinstallation, did you uninstall it fully before ?

I did not had any trouble with the computer vision part on kaggle before. So I wonder if the text part does not have something missing for the automatic installation. I will retry to run on of my old Fastai kernel on kaggle to see if this type of problem appear with the computer vision part of the library now.

**Comment by henry090** [comment]
> For the reinstallation, did you uninstall it fully before ?

installation to the new fresh env

**Comment by Cdk29** [comment]
I have forked an old kernel which was working fine with fastai, with a xresnet. I got a similar errror, so I guess something changed on the kaggle side.

**Comment by henry090** [comment]
I have just added a test and it worked. I cannot find your notebook. Could you share the link, again, please?

**Comment by Cdk29** [comment]
The notebook is here : https://www.kaggle.com/cdk292/baseline-ulmfit-fastai-and-r

**Comment by Cdk29** [comment]
Now it is tokenize_df() that bothered me when I tried to create a databunch : 

`Error in py_call_impl(callable, dots$args, dots$keywords): TypeError: tokenize_df() got an unexpected keyword argument 'res_col_name'`

**Comment by henry090** [comment]
@Cdk29 I think there might be conflicts with other python packages. Or maybe the python version. I am not sure.

```
Error in py_module_import(module, convert = convert): AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'
```

**Comment by henry090** [comment]
@Cdk29 I am using 

```
python:         /home/turgut/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.9.so
pythonhome:     /home/turgut/.local/share/r-miniconda/envs/r-reticulate:/home/turgut/.local/share/r-miniconda/envs/r-reticulate
version:        3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46)  [GCC 9.3.0]
numpy:          /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/numpy
numpy_version:  1.20.2
```

**Comment by Cdk29** [comment]
Maybe yes :/

I just remember that the fastai textbook mention that they interface with Spacy for the tokenization. Maybe this is missing in the R kernel of kaggle too.

**Comment by Cdk29** [comment]
Ahhh I think I got : 

https://github.com/fastai/fastai/blob/master/fastai/text/core.py#L211

def tokenize_df(df, text_cols, n_workers=defaults.cpus, rules=None, mark_fields=None,
                tok=None, tok_text_col="text"): 

I fastai.

In the R wrapper : 

tokenize_df(
  df,
  text_cols,
  n_workers = 6,
  rules = NULL,
  mark_fields = NULL,
  tok = NULL,
  **res_col_name = "text"**
)

I think one name changed in the main distribution of fastai, explaining the missalignement of the arguments.

**Comment by henry090** [comment]
Please try and let me know or open a PR?

**Comment by Cdk29** [comment]
@henry090 I will try it first to see. If it works I will open a PR after I changed my ~/.gitconfig file [as describe here](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch.) To avoid all the previous commit to come too.

**Comment by henry090** [comment]
@Cdk29 Maybe you will run your code as I do in Colab with miniconda installation??
https://colab.research.google.com/drive/1PiBECDM552No-5apVIB8LqUSdSqqJSi-?usp=sharing

```
  reticulate::install_miniconda()
  reticulate::conda_create('r-reticulate', packages = 'python==3.9')
  fastai::install_fastai(GPU = TRUE)
```

**Comment by Cdk29** [comment]
One day I will have to learn the API to got Kaggle's data to migrate to colab yes.

**Comment by Cdk29** [comment]
Hi ! 
I managed to passed the error by replacing the various occurrences of "res_col_name" by "tok_text_col".

I am still facing errors when trying to build a classifier, but more related to humain error when calling fastai i think.

**Comment by henry090** [comment]
Hi, I cannot see the page. Could you paste here the code an error, please?
![Screenshot from 2021-05-01 11-50-00](https://user-images.githubusercontent.com/38523699/116775300-622cdb80-aa73-11eb-9c42-84bea74e104f.png)

**Comment by Cdk29** [comment]
Hi ! I have some trouble too with kaggle at the moment.
I managed to got it working this morning on a sub part of the training set.
Yesterday after I solved the issue of "res_col_name" by changing it inside my fork to "tok_text_col" I forgot to remove the "train<-head(train)" that I put to test quicker. Once I put several labels and more than 6 training example in the dataset everything worked as expected.

So seems that replacing res_col_name by tok_text_col solved the issue on kaggle. But I am worried if you cannot replicate this on your local machine with a recent fastai installation.

**Comment by henry090** [comment]
Did you try this tutorial? Is it about text summarization?? https://eagerai.github.io/fastai/articles/textsummarize.html
I think this can be helpful however I am not sure. What do you think?

**Comment by Cdk29** [comment]
Hi ! The tutorial is nice but not connected to the current issue ^^

I had to replace on my fork variable name such as `res_col_name ` by `tok_text_col ` like here : https://github.com/Cdk29/fastai/commit/974677ad9d63fd4fa642a62583a5ae8b1610947b

This to match the change of variable name in fastai : https://github.com/fastai/fastai/blob/master/fastai/text/core.py#L211

The thing is : what should be do about it ? I can PR it into your repo, but this could create conflict with old fastai installation.
