### ISSUE TITLE
Issue in using fastai w/ GitHub actions?

### ISSUE THREAD

**Issue by oliviergimenez** [EagerAI/fastai#144]
First let me say that using fastai with R is just a game changer, many many thanks for dev this package 👏  

For a paper in review at the [Computo journal](https://computo.sfds.asso.fr/), I'm using GitHub actions to generate a compiled R Markdown notebook that is published to a gh-page - see [here](https://github.com/oliviergimenez/computo-deeplearning-occupany-lynx/blob/master/dl-occupancy-lynx-paper.Rmd) for a reproducible example that uses [an example from the fastai repo](https://github.com/EagerAI/fastai#tabular-data) which works fine locally on my laptop. 

Everything went well at the initial submission, but now that I'm about to resubmit, the build fails 😢 as can be seen [here](https://github.com/oliviergimenez/computo-deeplearning-occupany-lynx/runs/4670434258?check_suite_focus=true). The message I get is as follows:

<img width="1031" alt="Capture d’écran 2021-12-31 à 11 16 57" src="https://user-images.githubusercontent.com/12683635/147814669-8e16c652-55e0-495e-968c-8dedd83171de.png">

Note that I follow the recommendations to install the package - see lines 16-22 in [there](https://github.com/oliviergimenez/computo-deeplearning-occupany-lynx/blob/master/r-addons.R).

Any help would be much appreciated 😇 
Cheers, and happy new year ! 🎄 🥳

**Comment by turgut090** [comment]
Hi @oliviergimenez . Thanks for kind words!! =)
Happy New Year, as well@
Please, see my results for Mac OS https://github.com/EagerAI/fastai/runs/4678600620?check_suite_focus=true
The tests passed. Could you take a look and see what is different between our YAML files?

**Comment by oliviergimenez** [comment]
Hi @turgut090. Thank you so much for your help. Problem solved 🎊  Looking at your yml file helped 👍  In case it's useful, here are the lines of code I used https://github.com/oliviergimenez/computo-deeplearning-occupany-lynx/blob/master/r-addons.R.
