### ISSUE TITLE
Problem with get_image_files( ) 

### ISSUE THREAD

**Issue by MelihOrel** [EagerAI/fastai#146]
Hi, I am trying to use this function get_image_files( ) but, this error showed up:

`Error: $ operator is invalid for atomic vectors`

I have tried this code for a solution, it's not worked: 

`fastai::install_fastai(gpu = FALSE, cuda_version = '10', overwrite = FALSE)
[1] "Fastai is installed!"`

are there any other solutions?

Best regards.

**Comment by turgut090** [comment]
Hi, sorry for late reply.

Is fastai available in your local?

```
reticulate::py_module_available('fastai')
```

Did you follow these steps?

```
require(devtools)
install_version("reticulate", version = "1.21", repos = "http://cran.us.r-project.org")
fastai::install_fastai(gpu = FALSE, cuda_version = '10', overwrite = FALSE)
```
