### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mubashirqasim** [EagerAI/fastai#147]
Hi there,

I am getting the following error when I try to run this part. Any thoughts?

`fastai::install_fastai(gpu = FALSE, cuda_version = '10', overwrite = FALSE)`

r-miniconda/envs/r-reticulate/python.exe" -m pip install --upgrade "torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html" "IPython" "pydicom" "kornia" "opencv-python" "scikit-image" "timm" "fastinference[interp]" 
ERROR: Invalid requirement: 'torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html'

Thank you very much for your time.

Kind regards,

M

**Comment by turgut090** [comment]
Hi, AFAIR the issue is related to reticulate.
Please, do the following and try to reinstall fastai.

```
require(devtools)
install_version("reticulate", version = "1.21", repos = "http://cran.us.r-project.org")
```

**Comment by mubashirqasim** [comment]
Great, it worked... I thought it could not find the specified torch versions.

**Comment by turgut090** [comment]
The new CRAN version does not require reticulate downgrade. Thanks
